name: Integration_Tests

on:
  repository_dispatch:
    types: integrationTests

jobs:
  respond:
    name: Calls the callback being passed in
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup yq
        uses: mikefarah/yq@v4.33.3

      - name: Extract mongo image
        id: extract_mongo_image
        run: |
          image=$(yq '.spec.template.spec.containers[] | select(.name == "mongo") | .image' pxbbq-demo/mongodb.yaml | head -n 1)
          echo "mongoImage=${image}" >> $GITHUB_ENV

      - name: Evaluate mongoImage
        run: |
          if [ "${{ env.mongoImage }}" = "mongo:6.0.2" ]; then
            echo "mongoStatus=false" >> $GITHUB_ENV
          else
            echo "mongoStatus=true" >> $GITHUB_ENV
          fi

      - name: getToken
        id: getToken
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://auth.cloud.armory.io/oauth/token"
          method: "POST"
          customHeaders: '{ "Content-Type": "application/x-www-form-urlencoded" }'
          data: 'audience=https://api.cloud.armory.io&grant_type=client_credentials&client_id=${{ secrets.CDAAS_CLIENT_ID }}&client_secret=${{ secrets.CDAAS_CLIENT_SECRET }}'
          
      - name: callCallback
        id: callCallback
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ github.event.client_payload.callbackUri }}
          method: 'POST'
          bearerToken: ${{ fromJSON(steps.getToken.outputs.response).access_token }}
          customHeaders: '{ "Content-Type": "application/json" }'
          data: '{ "success": ${{ env.mongoStatus }}, "mdMessage": "Webhook successful: no errors found in logs service: ${{ github.event.client_payload.service }}" }'

      - name: show http response
        run: echo ${{ steps.callCallback.outputs.response }}
